"""Circular Resolution Engine.

Milestone 7B translates broad rules-engine recommendations into specific,
evidence-controlled circular economy intervention plans. It never overrides the
locked recommendation, risk level or human-review flag.
"""

from __future__ import annotations

from collections import Counter
from typing import Any

from app import models
from app.circular_resolution.playbook import MaterialPlaybook, get_playbook
from app.circular_resolution.quality_gates import claim_boundary_for, confidence_notes, decision_gates_for, route_strength


def _contains_any(text: str, keywords: list[str]) -> bool:
    lowered = text.lower()
    return any(keyword in lowered for keyword in keywords)


def _stream_text(stream: models.IndustrialStream) -> str:
    return " ".join(
        str(value or "")
        for value in [
            stream.stream_id,
            stream.stream_name,
            stream.material,
            stream.source_process,
            stream.current_route,
            stream.department,
            stream.supplier,
            stream.notes,
        ]
    ).lower()


def _circular_problem(stream: models.IndustrialStream, recommendation: models.CircularRecommendation, playbook: MaterialPlaybook) -> str:
    text = _stream_text(stream)
    if recommendation.human_review_required or recommendation.risk_level in {"high", "blocked"}:
        return (
            f"{stream.stream_name} is a controlled industrial stream from {stream.source_process}. The immediate circular economy problem is not route selection; it is resolving risk, classification, contamination and evidence before any recovery, reuse or valorisation option is proposed."
        )
    if _contains_any(text, ["packaging", "carton", "wrap", "pallet", "crate", "tote", "insert"]):
        return (
            f"{stream.stream_name} appears to be a recurring packaging or logistics stream. The circular economy issue is whether one-way material use can be prevented through supplier redesign, returnable packaging or reverse logistics before recycling is used as fallback."
        )
    if _contains_any(text, ["offcut", "trim", "swarf", "reject", "scrap", "purge"]):
        return (
            f"{stream.stream_name} is generated by {stream.source_process}, suggesting a recurring production loss. The circular economy issue is whether the stream can be prevented, segregated or kept in a higher-value loop instead of being treated as low-value waste."
        )
    if _contains_any(text, ["heat", "water", "sludge", "residue"]):
        return (
            f"{stream.stream_name} is a process resource stream. The circular economy issue is whether resource use can be reduced, recovered or looped safely with sufficient technical and compliance evidence."
        )
    return (
        f"{stream.stream_name} has been screened as a {recommendation.circular_strategy_category} opportunity. The circular economy issue is to retain material value and avoid unsupported claims while evidence gaps are resolved."
    )


def _resolution_idea(stream: models.IndustrialStream, recommendation: models.CircularRecommendation, playbook: MaterialPlaybook) -> str:
    text = _stream_text(stream)
    if recommendation.human_review_required or recommendation.risk_level in {"high", "blocked"}:
        if _contains_any(text, ["grease", "fog", "canteen"]):
            return (
                "Treat this as a controlled FOG/organic-residue review. Confirm classification, contamination profile, contractor acceptance and maintenance records first. Only then screen food-waste prevention, grease-load reduction, authorised FOG recovery, anaerobic digestion or specialist treatment options."
            )
        if _contains_any(text, ["battery", "lithium"]):
            return (
                "Do not frame this as a circular quick win. Isolate the stream under specialist battery/WEEE handling rules, confirm battery chemistry and damage status, and use authorised treatment or supplier take-back evidence before considering recovery."
            )
        if _contains_any(text, ["solvent", "acetone", "chemical", "adhesive", "oil"]):
            return (
                "Run a controlled chemical-stream review. Confirm SDS, hazardous classification, contamination profile, storage conditions and authorised contractor acceptance before considering solvent recovery, supplier return, substitution or disposal."
            )
        return (
            "Run a controlled review workflow before any circular intervention. Resolve hazardous status, contamination, acceptance criteria and authorised handling evidence, then reassess whether prevention, specialist recovery or compliant disposal is appropriate."
        )

    category = (recommendation.circular_strategy_category or "").lower()
    if "reduce" in category:
        return (
            f"Start with a source-reduction pilot for {stream.source_process}. Identify the root cause of {stream.stream_name}, test process/specification changes, and measure whether the stream can be reduced before selecting an end-of-pipe route."
        )
    if "supplier take-back" in category:
        return (
            f"Design a supplier-loop intervention with {stream.supplier}. Confirm take-back terms, acceptance criteria, reverse-logistics responsibilities and evidence requirements, then pilot the loop on a controlled subset of the stream."
        )
    if "internal reuse" in category:
        return (
            f"Screen internal reuse or returnable packaging first. Map internal demand, storage constraints and quality requirements, then test whether {stream.stream_name} can replace a purchased input or one-way packaging flow."
        )
    if "industrial symbiosis" in category:
        if "heat" in text:
            return (
                "Start with heat mapping rather than waste diversion. Measure temperature, duration, operating hours and nearby heat demand, then screen internal heat recovery before external symbiosis."
            )
        if "water" in text:
            return (
                "Frame this as a water-efficiency and reuse opportunity. Measure quality, contaminant profile and flow rate, then screen filtration, closed-loop reuse or lower-grade internal reuse before treatment/discharge."
            )
        return (
            f"Develop a by-product valorisation screen. Confirm composition, stability, volume consistency and liability boundaries, then identify internal users or external partner types that could safely use {stream.stream_name} as an input."
        )
    if "closed-loop" in category:
        return (
            f"Create a quality-retention loop for {stream.stream_name}. Separate the material at source, document grade/composition, confirm contamination limits and test a supplier or recycler route that keeps the material in a comparable application."
        )
    if "open-loop" in category:
        return (
            f"Use open-loop recycling or specialist recovery as a controlled lower-value route. First confirm material specification, contamination limits and acceptance criteria so the stream does not contaminate higher-value loops."
        )
    return (
        f"Use the current recommendation as an evidence-improvement plan. Close material composition, contamination, supplier and route evidence gaps before changing the current route for {stream.stream_name}."
    )


def _implementation_steps(stream: models.IndustrialStream, recommendation: models.CircularRecommendation, playbook: MaterialPlaybook) -> list[str]:
    if recommendation.human_review_required or recommendation.risk_level in {"high", "blocked"}:
        return [
            "Confirm hazardous/non-hazardous classification and contamination profile.",
            "Check current route documentation, contractor authorisation and acceptance criteria.",
            "Keep the stream segregated and controlled while evidence is unresolved.",
            "Assess source-prevention options that do not create safety or compliance risk.",
            "Re-run the circular recommendation only after the review gate is closed.",
        ]
    steps = [
        f"Map where {stream.stream_name} is generated within {stream.source_process}.",
        f"Apply the playbook focus: {playbook.focus}.",
        "Collect baseline quantity, cost, contamination and current-route evidence for a defined period.",
        "Select one controlled pilot route rather than changing all streams at once.",
        "Document supplier/contractor acceptance criteria and rejection conditions.",
        "Track KPIs and update the evidence register before making any claim.",
    ]
    category = (recommendation.circular_strategy_category or "").lower()
    if "closed-loop" in category:
        steps.insert(2, "Set up source segregation so material grade and contamination are controlled before collection.")
    elif "supplier" in category:
        steps.insert(2, f"Ask {stream.supplier} for take-back, reverse-logistics and documentation requirements.")
    elif "reduce" in category:
        steps.insert(2, "Run a root-cause review to identify avoidable scrap, over-specification or setup losses.")
    elif "industrial symbiosis" in category:
        steps.insert(2, "Define composition, volume consistency and likely partner types before any external approach.")
    return steps


def _supplier_action(stream: models.IndustrialStream, recommendation: models.CircularRecommendation, playbook: MaterialPlaybook) -> str:
    if not stream.supplier or stream.supplier.lower() in {"unknown", "various suppliers"}:
        return "Identify the responsible supplier or contractor before drafting a supplier-loop action. For mixed suppliers, rank the top contributors by quantity/frequency first."
    if recommendation.human_review_required:
        return (
            f"Ask {stream.supplier} or the current contractor for classification, acceptance criteria, authorised handling evidence and any safe recovery/take-back option. Do not request implementation until the review gate is closed."
        )
    return (
        f"Ask {stream.supplier} for circular options: take-back, returnable packaging, recycled-content evidence, acceptance/rejection criteria, collection frequency, contract clauses and documentation suitable for audit."
    )


def _process_action(stream: models.IndustrialStream, recommendation: models.CircularRecommendation, playbook: MaterialPlaybook) -> str:
    text = _stream_text(stream)
    if "grease" in text or "canteen" in text:
        return "Review kitchen practices, food-waste separation, grease-trap maintenance frequency and contractor records to reduce FOG load before considering recovery."
    if "water" in text:
        return "Review rinse settings, flow controls, contaminant sources and reuse quality requirements before proposing water-loop reuse."
    if "heat" in text:
        return "Measure temperature, operating hours and internal heat demand before proposing heat recovery or external heat symbiosis."
    if "pack" in text or "pallet" in text or "crate" in text or "tote" in text:
        return "Review packaging specification, damage rate, delivery frequency, storage space and return logistics before relying on recycling."
    if "solvent" in text or "chemical" in text or "oil" in text:
        return "Review dosing, cleaning frequency, substitution options and segregation of chemical streams before considering recovery."
    return f"Review {stream.source_process} for avoidable losses, over-ordering, set-up scrap, quality rejects or handling practices that create the stream."


def _symbiosis_action(stream: models.IndustrialStream, recommendation: models.CircularRecommendation, playbook: MaterialPlaybook) -> str:
    text = _stream_text(stream)
    if recommendation.human_review_required:
        return "Do not approach external users until legal status, contamination and acceptance criteria are confirmed. Industrial symbiosis remains a controlled screening option only."
    if "heat" in text:
        return "Likely symbiosis route: internal heat recovery first, then nearby low-temperature heat users if temperature, timing and distance are suitable."
    if "water" in text:
        return "Likely symbiosis route: internal reuse or treatment loop first. External use requires water-quality and permit evidence."
    if "organic" in stream.material.lower() or "starch" in text or "coffee" in text or "biomass" in text:
        return "Likely partner types: anaerobic digestion operator, composting/soil improver route, bio-based material processor or authorised organic recovery contractor, subject to composition and acceptance criteria."
    if "mineral" in stream.material.lower() or "sludge" in text:
        return "Likely partner types: specialist mineral processor or construction-material processor only after composition, contamination and legal status are evidenced."
    if recommendation.industrial_symbiosis_opportunity in {"possible", "screening recommended"} or "industrial symbiosis" in recommendation.circular_strategy_category.lower():
        return "Identify partner types based on composition, volume consistency, storage and liability boundaries before contacting external organisations."
    return "Not the primary route. Consider symbiosis only if prevention, reuse, supplier loop or closed-loop recycling is not feasible."


def _pilot_plan(stream: models.IndustrialStream, recommendation: models.CircularRecommendation, playbook: MaterialPlaybook) -> str:
    if recommendation.human_review_required:
        return (
            "Pilot type: evidence-gathering review only. Timebox a 4-6 week review to confirm classification, contamination, contractor acceptance and source-prevention options. No physical route change should occur until gates are closed."
        )
    duration = "6-8 weeks"
    if recommendation.estimated_annual_waste_diverted_kg > 10000:
        duration = "8 weeks"
    return (
        f"Pilot type: controlled validation pilot for {duration}. Use one department or supplier lane, track baseline and pilot quantities, record acceptance/rejection evidence, compare costs, and update the evidence register before scaling."
    )


def build_resolution_plan(
    stream: models.IndustrialStream,
    recommendation: models.CircularRecommendation,
) -> dict[str, Any]:
    playbook = get_playbook(stream.material)
    evidence_required = list(dict.fromkeys(playbook.evidence_required + [item.strip() for item in recommendation.missing_data.split(";") if item.strip() and item.strip() not in {"none recorded", "none identified for MVP fields"}]))

    return {
        "stream_id": stream.stream_id,
        "stream_name": stream.stream_name,
        "material": stream.material,
        "department": stream.department,
        "supplier": stream.supplier,
        "locked_recommendation": recommendation.recommended_circular_action,
        "circular_strategy_category": recommendation.circular_strategy_category,
        "risk_level": recommendation.risk_level,
        "human_review_required": recommendation.human_review_required,
        "rule_applied": recommendation.rule_applied,
        "material_playbook_focus": playbook.focus,
        "circular_problem": _circular_problem(stream, recommendation, playbook),
        "specific_resolution_idea": _resolution_idea(stream, recommendation, playbook),
        "why_this_is_circular_economy": playbook.circular_economy_reason,
        "value_retention_logic": playbook.value_retention_logic,
        "implementation_steps": _implementation_steps(stream, recommendation, playbook),
        "supplier_or_procurement_action": _supplier_action(stream, recommendation, playbook),
        "process_redesign_action": _process_action(stream, recommendation, playbook),
        "industrial_symbiosis_action": _symbiosis_action(stream, recommendation, playbook),
        "pilot_plan": _pilot_plan(stream, recommendation, playbook),
        "kpis": playbook.pilot_kpis,
        "evidence_required": evidence_required or ["no additional evidence identified by MVP fields"],
        "decision_gates": decision_gates_for(stream, recommendation),
        "claim_boundary": claim_boundary_for(recommendation),
        "fallback_route": playbook.fallback_route,
        "confidence_notes": confidence_notes(stream, recommendation),
        "circularity_route_strength": route_strength(recommendation),
        "estimated_annual_waste_diverted_kg": recommendation.estimated_annual_waste_diverted_kg,
        "estimated_annual_disposal_cost_avoided": recommendation.estimated_annual_disposal_cost_avoided,
    }


def build_resolution_plans(
    streams: list[models.IndustrialStream],
    recommendations: list[models.CircularRecommendation],
) -> list[dict[str, Any]]:
    stream_lookup = {stream.stream_id: stream for stream in streams}
    plans: list[dict[str, Any]] = []
    for recommendation in sorted(recommendations, key=lambda rec: rec.stream_id):
        stream = stream_lookup.get(recommendation.stream_id)
        if stream:
            plans.append(build_resolution_plan(stream, recommendation))
    return plans


def build_resolution_summary(plans: list[dict[str, Any]]) -> dict[str, Any]:
    strengths = Counter(plan["circularity_route_strength"] for plan in plans)
    playbooks = Counter(plan["material_playbook_focus"] for plan in plans)
    controlled = sum(1 for plan in plans if plan["human_review_required"])
    claim_blocked = sum(1 for plan in plans if plan["claim_boundary"].startswith("Not claim-ready"))
    quick_candidates = [
        plan
        for plan in plans
        if not plan["human_review_required"]
        and plan["risk_level"] == "low"
        and plan["circularity_route_strength"].startswith(("high", "medium-high"))
    ]
    quick_candidates = sorted(
        quick_candidates,
        key=lambda plan: (plan["estimated_annual_waste_diverted_kg"], plan["estimated_annual_disposal_cost_avoided"]),
        reverse=True,
    )[:5]
    return {
        "total_plans": len(plans),
        "controlled_review_plans": controlled,
        "claim_blocked_or_not_ready": claim_blocked,
        "route_strength_breakdown": dict(strengths),
        "playbook_focus_breakdown": dict(playbooks),
        "top_validation_candidates": [
            {
                "stream_id": plan["stream_id"],
                "stream_name": plan["stream_name"],
                "specific_resolution_idea": plan["specific_resolution_idea"],
                "estimated_annual_waste_diverted_kg": plan["estimated_annual_waste_diverted_kg"],
                "estimated_annual_disposal_cost_avoided": plan["estimated_annual_disposal_cost_avoided"],
            }
            for plan in quick_candidates
        ],
        "method_note": (
            "Resolution plans are generated from locked rules-engine outputs plus material-specific circular economy playbooks. "
            "They are intervention designs for screening and pilot planning, not verified operational instructions or environmental claims."
        ),
    }
